# Generated by Django 4.2.6 on 2023-11-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomments',
            name='text',
            field=models.TextField(default='', max_length=3500, verbose_name='Comment'),
        ),
    ]
